// Generated by gencpp from file robotont_msgs/LedModulePixel.msg
// DO NOT EDIT!


#ifndef ROBOTONT_MSGS_MESSAGE_LEDMODULEPIXEL_H
#define ROBOTONT_MSGS_MESSAGE_LEDMODULEPIXEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotont_msgs/ColorRGB.h>

namespace robotont_msgs
{
template <class ContainerAllocator>
struct LedModulePixel_
{
  typedef LedModulePixel_<ContainerAllocator> Type;

  LedModulePixel_()
    : idx(0)
    , color()  {
    }
  LedModulePixel_(const ContainerAllocator& _alloc)
    : idx(0)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _idx_type;
  _idx_type idx;

   typedef  ::robotont_msgs::ColorRGB_<ContainerAllocator>  _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::robotont_msgs::LedModulePixel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotont_msgs::LedModulePixel_<ContainerAllocator> const> ConstPtr;

}; // struct LedModulePixel_

typedef ::robotont_msgs::LedModulePixel_<std::allocator<void> > LedModulePixel;

typedef boost::shared_ptr< ::robotont_msgs::LedModulePixel > LedModulePixelPtr;
typedef boost::shared_ptr< ::robotont_msgs::LedModulePixel const> LedModulePixelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotont_msgs::LedModulePixel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotont_msgs::LedModulePixel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotont_msgs::LedModulePixel_<ContainerAllocator1> & lhs, const ::robotont_msgs::LedModulePixel_<ContainerAllocator2> & rhs)
{
  return lhs.idx == rhs.idx &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotont_msgs::LedModulePixel_<ContainerAllocator1> & lhs, const ::robotont_msgs::LedModulePixel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotont_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotont_msgs::LedModulePixel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotont_msgs::LedModulePixel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotont_msgs::LedModulePixel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotont_msgs::LedModulePixel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotont_msgs::LedModulePixel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotont_msgs::LedModulePixel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotont_msgs::LedModulePixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e8715e10cbaf5916ac0df9876db527d";
  }

  static const char* value(const ::robotont_msgs::LedModulePixel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e8715e10cbaf591ULL;
  static const uint64_t static_value2 = 0x6ac0df9876db527dULL;
};

template<class ContainerAllocator>
struct DataType< ::robotont_msgs::LedModulePixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotont_msgs/LedModulePixel";
  }

  static const char* value(const ::robotont_msgs::LedModulePixel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotont_msgs::LedModulePixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 idx\n"
"robotont_msgs/ColorRGB color\n"
"\n"
"================================================================================\n"
"MSG: robotont_msgs/ColorRGB\n"
"#Red, Green, Blue intensities in range of 0-255.\n"
"uint8 r\n"
"uint8 g\n"
"uint8 b\n"
;
  }

  static const char* value(const ::robotont_msgs::LedModulePixel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotont_msgs::LedModulePixel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idx);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LedModulePixel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotont_msgs::LedModulePixel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotont_msgs::LedModulePixel_<ContainerAllocator>& v)
  {
    s << indent << "idx: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.idx);
    s << indent << "color: ";
    s << std::endl;
    Printer< ::robotont_msgs::ColorRGB_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTONT_MSGS_MESSAGE_LEDMODULEPIXEL_H
