// Generated by gencpp from file robotont_msgs/LedModuleSegment.msg
// DO NOT EDIT!


#ifndef ROBOTONT_MSGS_MESSAGE_LEDMODULESEGMENT_H
#define ROBOTONT_MSGS_MESSAGE_LEDMODULESEGMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robotont_msgs/ColorRGB.h>

namespace robotont_msgs
{
template <class ContainerAllocator>
struct LedModuleSegment_
{
  typedef LedModuleSegment_<ContainerAllocator> Type;

  LedModuleSegment_()
    : idx_start(0)
    , colors()  {
    }
  LedModuleSegment_(const ContainerAllocator& _alloc)
    : idx_start(0)
    , colors(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _idx_start_type;
  _idx_start_type idx_start;

   typedef std::vector< ::robotont_msgs::ColorRGB_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robotont_msgs::ColorRGB_<ContainerAllocator> >::other >  _colors_type;
  _colors_type colors;





  typedef boost::shared_ptr< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> const> ConstPtr;

}; // struct LedModuleSegment_

typedef ::robotont_msgs::LedModuleSegment_<std::allocator<void> > LedModuleSegment;

typedef boost::shared_ptr< ::robotont_msgs::LedModuleSegment > LedModuleSegmentPtr;
typedef boost::shared_ptr< ::robotont_msgs::LedModuleSegment const> LedModuleSegmentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotont_msgs::LedModuleSegment_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotont_msgs::LedModuleSegment_<ContainerAllocator1> & lhs, const ::robotont_msgs::LedModuleSegment_<ContainerAllocator2> & rhs)
{
  return lhs.idx_start == rhs.idx_start &&
    lhs.colors == rhs.colors;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotont_msgs::LedModuleSegment_<ContainerAllocator1> & lhs, const ::robotont_msgs::LedModuleSegment_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotont_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "074116e38328a837ef6928799ed4707a";
  }

  static const char* value(const ::robotont_msgs::LedModuleSegment_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x074116e38328a837ULL;
  static const uint64_t static_value2 = 0xef6928799ed4707aULL;
};

template<class ContainerAllocator>
struct DataType< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotont_msgs/LedModuleSegment";
  }

  static const char* value(const ::robotont_msgs::LedModuleSegment_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 idx_start\n"
"robotont_msgs/ColorRGB[] colors\n"
"\n"
"================================================================================\n"
"MSG: robotont_msgs/ColorRGB\n"
"#Red, Green, Blue intensities in range of 0-255.\n"
"uint8 r\n"
"uint8 g\n"
"uint8 b\n"
;
  }

  static const char* value(const ::robotont_msgs::LedModuleSegment_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idx_start);
      stream.next(m.colors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LedModuleSegment_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotont_msgs::LedModuleSegment_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotont_msgs::LedModuleSegment_<ContainerAllocator>& v)
  {
    s << indent << "idx_start: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.idx_start);
    s << indent << "colors[]" << std::endl;
    for (size_t i = 0; i < v.colors.size(); ++i)
    {
      s << indent << "  colors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robotont_msgs::ColorRGB_<ContainerAllocator> >::stream(s, indent + "    ", v.colors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTONT_MSGS_MESSAGE_LEDMODULESEGMENT_H
