// Generated by gencpp from file robotont_msgs/PowerSupply.msg
// DO NOT EDIT!


#ifndef ROBOTONT_MSGS_MESSAGE_POWERSUPPLY_H
#define ROBOTONT_MSGS_MESSAGE_POWERSUPPLY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotont_msgs
{
template <class ContainerAllocator>
struct PowerSupply_
{
  typedef PowerSupply_<ContainerAllocator> Type;

  PowerSupply_()
    : current(0.0)
    , voltage(0.0)
    , estop_pressed(false)  {
    }
  PowerSupply_(const ContainerAllocator& _alloc)
    : current(0.0)
    , voltage(0.0)
    , estop_pressed(false)  {
  (void)_alloc;
    }



   typedef float _current_type;
  _current_type current;

   typedef float _voltage_type;
  _voltage_type voltage;

   typedef uint8_t _estop_pressed_type;
  _estop_pressed_type estop_pressed;





  typedef boost::shared_ptr< ::robotont_msgs::PowerSupply_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotont_msgs::PowerSupply_<ContainerAllocator> const> ConstPtr;

}; // struct PowerSupply_

typedef ::robotont_msgs::PowerSupply_<std::allocator<void> > PowerSupply;

typedef boost::shared_ptr< ::robotont_msgs::PowerSupply > PowerSupplyPtr;
typedef boost::shared_ptr< ::robotont_msgs::PowerSupply const> PowerSupplyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotont_msgs::PowerSupply_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotont_msgs::PowerSupply_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robotont_msgs::PowerSupply_<ContainerAllocator1> & lhs, const ::robotont_msgs::PowerSupply_<ContainerAllocator2> & rhs)
{
  return lhs.current == rhs.current &&
    lhs.voltage == rhs.voltage &&
    lhs.estop_pressed == rhs.estop_pressed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robotont_msgs::PowerSupply_<ContainerAllocator1> & lhs, const ::robotont_msgs::PowerSupply_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robotont_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robotont_msgs::PowerSupply_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotont_msgs::PowerSupply_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotont_msgs::PowerSupply_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotont_msgs::PowerSupply_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotont_msgs::PowerSupply_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotont_msgs::PowerSupply_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotont_msgs::PowerSupply_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77b9b8496ff236da784fb46719fa61bb";
  }

  static const char* value(const ::robotont_msgs::PowerSupply_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77b9b8496ff236daULL;
  static const uint64_t static_value2 = 0x784fb46719fa61bbULL;
};

template<class ContainerAllocator>
struct DataType< ::robotont_msgs::PowerSupply_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotont_msgs/PowerSupply";
  }

  static const char* value(const ::robotont_msgs::PowerSupply_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotont_msgs::PowerSupply_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Measured current consumption \n"
"float32 current\n"
"\n"
"# Measured voltage level of the battery\n"
"float32 voltage\n"
"\n"
"# Indicates whether e-stop button is pressed or not\n"
"bool estop_pressed\n"
;
  }

  static const char* value(const ::robotont_msgs::PowerSupply_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotont_msgs::PowerSupply_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
      stream.next(m.voltage);
      stream.next(m.estop_pressed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PowerSupply_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotont_msgs::PowerSupply_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotont_msgs::PowerSupply_<ContainerAllocator>& v)
  {
    s << indent << "current: ";
    Printer<float>::stream(s, indent + "  ", v.current);
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    s << indent << "estop_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.estop_pressed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTONT_MSGS_MESSAGE_POWERSUPPLY_H
