# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from leap_motion_controller/Set.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import leap_motion_controller.msg
import std_msgs.msg

class Set(genpy.Message):
  _md5sum = "a1f63767b76560dd9b983103a3c6a895"
  _type = "leap_motion_controller/Set"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# For position, Leap Motion Controller uses '_optical' axis orientation, i.e.:
#    z forward
#    x right
#    y down

std_msgs/Header header

leap_motion_controller/Hand left_hand

leap_motion_controller/Hand right_hand

uint8 extended_fingers
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: leap_motion_controller/Hand
# For position, Leap Motion Controller uses '_optical' axis orientation, i.e.:
#    z forward
#    x right
#    y down

bool is_present					# TRUE if this hand is a valid hand (left or right), FALSE otherwise.
geometry_msgs/PoseStamped palm_pose		# Contains the center position of the palm in meters from the Leap Motion Controller origin and the quaternion orientation of the palm.
geometry_msgs/Vector3Stamped palm_velocity	# The rate of change of the palm position in meters per second. 
float32 sphere_radius				# The radius of a sphere fit to the curvature of this hand. This sphere is placed roughly as if the hand were holding a ball. Thus the size of the sphere decreases as the fingers are curled into a fist.
float32 pinch_strength				# The strength is zero for an open hand, and blends to 1.0 when a pinching hand pose is recognized.
bool key_tap					# TRUE if KEY_TAP gesture has been detected on this hand, FALSE otherwise.
================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3Stamped
# This represents a Vector3 with reference coordinate frame and timestamp
Header header
Vector3 vector

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','left_hand','right_hand','extended_fingers']
  _slot_types = ['std_msgs/Header','leap_motion_controller/Hand','leap_motion_controller/Hand','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,left_hand,right_hand,extended_fingers

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Set, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_hand is None:
        self.left_hand = leap_motion_controller.msg.Hand()
      if self.right_hand is None:
        self.right_hand = leap_motion_controller.msg.Hand()
      if self.extended_fingers is None:
        self.extended_fingers = 0
    else:
      self.header = std_msgs.msg.Header()
      self.left_hand = leap_motion_controller.msg.Hand()
      self.right_hand = leap_motion_controller.msg.Hand()
      self.extended_fingers = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.left_hand.is_present, _x.left_hand.palm_pose.header.seq, _x.left_hand.palm_pose.header.stamp.secs, _x.left_hand.palm_pose.header.stamp.nsecs))
      _x = self.left_hand.palm_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.left_hand.palm_pose.pose.position.x, _x.left_hand.palm_pose.pose.position.y, _x.left_hand.palm_pose.pose.position.z, _x.left_hand.palm_pose.pose.orientation.x, _x.left_hand.palm_pose.pose.orientation.y, _x.left_hand.palm_pose.pose.orientation.z, _x.left_hand.palm_pose.pose.orientation.w, _x.left_hand.palm_velocity.header.seq, _x.left_hand.palm_velocity.header.stamp.secs, _x.left_hand.palm_velocity.header.stamp.nsecs))
      _x = self.left_hand.palm_velocity.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d2f2B3I().pack(_x.left_hand.palm_velocity.vector.x, _x.left_hand.palm_velocity.vector.y, _x.left_hand.palm_velocity.vector.z, _x.left_hand.sphere_radius, _x.left_hand.pinch_strength, _x.left_hand.key_tap, _x.right_hand.is_present, _x.right_hand.palm_pose.header.seq, _x.right_hand.palm_pose.header.stamp.secs, _x.right_hand.palm_pose.header.stamp.nsecs))
      _x = self.right_hand.palm_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.right_hand.palm_pose.pose.position.x, _x.right_hand.palm_pose.pose.position.y, _x.right_hand.palm_pose.pose.position.z, _x.right_hand.palm_pose.pose.orientation.x, _x.right_hand.palm_pose.pose.orientation.y, _x.right_hand.palm_pose.pose.orientation.z, _x.right_hand.palm_pose.pose.orientation.w, _x.right_hand.palm_velocity.header.seq, _x.right_hand.palm_velocity.header.stamp.secs, _x.right_hand.palm_velocity.header.stamp.nsecs))
      _x = self.right_hand.palm_velocity.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d2f2B().pack(_x.right_hand.palm_velocity.vector.x, _x.right_hand.palm_velocity.vector.y, _x.right_hand.palm_velocity.vector.z, _x.right_hand.sphere_radius, _x.right_hand.pinch_strength, _x.right_hand.key_tap, _x.extended_fingers))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_hand is None:
        self.left_hand = leap_motion_controller.msg.Hand()
      if self.right_hand is None:
        self.right_hand = leap_motion_controller.msg.Hand()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.left_hand.is_present, _x.left_hand.palm_pose.header.seq, _x.left_hand.palm_pose.header.stamp.secs, _x.left_hand.palm_pose.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.left_hand.is_present = bool(self.left_hand.is_present)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.palm_pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.left_hand.palm_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.left_hand.palm_pose.pose.position.x, _x.left_hand.palm_pose.pose.position.y, _x.left_hand.palm_pose.pose.position.z, _x.left_hand.palm_pose.pose.orientation.x, _x.left_hand.palm_pose.pose.orientation.y, _x.left_hand.palm_pose.pose.orientation.z, _x.left_hand.palm_pose.pose.orientation.w, _x.left_hand.palm_velocity.header.seq, _x.left_hand.palm_velocity.header.stamp.secs, _x.left_hand.palm_velocity.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.palm_velocity.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.left_hand.palm_velocity.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 46
      (_x.left_hand.palm_velocity.vector.x, _x.left_hand.palm_velocity.vector.y, _x.left_hand.palm_velocity.vector.z, _x.left_hand.sphere_radius, _x.left_hand.pinch_strength, _x.left_hand.key_tap, _x.right_hand.is_present, _x.right_hand.palm_pose.header.seq, _x.right_hand.palm_pose.header.stamp.secs, _x.right_hand.palm_pose.header.stamp.nsecs,) = _get_struct_3d2f2B3I().unpack(str[start:end])
      self.left_hand.key_tap = bool(self.left_hand.key_tap)
      self.right_hand.is_present = bool(self.right_hand.is_present)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.palm_pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.right_hand.palm_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.right_hand.palm_pose.pose.position.x, _x.right_hand.palm_pose.pose.position.y, _x.right_hand.palm_pose.pose.position.z, _x.right_hand.palm_pose.pose.orientation.x, _x.right_hand.palm_pose.pose.orientation.y, _x.right_hand.palm_pose.pose.orientation.z, _x.right_hand.palm_pose.pose.orientation.w, _x.right_hand.palm_velocity.header.seq, _x.right_hand.palm_velocity.header.stamp.secs, _x.right_hand.palm_velocity.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.palm_velocity.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.right_hand.palm_velocity.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.right_hand.palm_velocity.vector.x, _x.right_hand.palm_velocity.vector.y, _x.right_hand.palm_velocity.vector.z, _x.right_hand.sphere_radius, _x.right_hand.pinch_strength, _x.right_hand.key_tap, _x.extended_fingers,) = _get_struct_3d2f2B().unpack(str[start:end])
      self.right_hand.key_tap = bool(self.right_hand.key_tap)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.left_hand.is_present, _x.left_hand.palm_pose.header.seq, _x.left_hand.palm_pose.header.stamp.secs, _x.left_hand.palm_pose.header.stamp.nsecs))
      _x = self.left_hand.palm_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.left_hand.palm_pose.pose.position.x, _x.left_hand.palm_pose.pose.position.y, _x.left_hand.palm_pose.pose.position.z, _x.left_hand.palm_pose.pose.orientation.x, _x.left_hand.palm_pose.pose.orientation.y, _x.left_hand.palm_pose.pose.orientation.z, _x.left_hand.palm_pose.pose.orientation.w, _x.left_hand.palm_velocity.header.seq, _x.left_hand.palm_velocity.header.stamp.secs, _x.left_hand.palm_velocity.header.stamp.nsecs))
      _x = self.left_hand.palm_velocity.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d2f2B3I().pack(_x.left_hand.palm_velocity.vector.x, _x.left_hand.palm_velocity.vector.y, _x.left_hand.palm_velocity.vector.z, _x.left_hand.sphere_radius, _x.left_hand.pinch_strength, _x.left_hand.key_tap, _x.right_hand.is_present, _x.right_hand.palm_pose.header.seq, _x.right_hand.palm_pose.header.stamp.secs, _x.right_hand.palm_pose.header.stamp.nsecs))
      _x = self.right_hand.palm_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.right_hand.palm_pose.pose.position.x, _x.right_hand.palm_pose.pose.position.y, _x.right_hand.palm_pose.pose.position.z, _x.right_hand.palm_pose.pose.orientation.x, _x.right_hand.palm_pose.pose.orientation.y, _x.right_hand.palm_pose.pose.orientation.z, _x.right_hand.palm_pose.pose.orientation.w, _x.right_hand.palm_velocity.header.seq, _x.right_hand.palm_velocity.header.stamp.secs, _x.right_hand.palm_velocity.header.stamp.nsecs))
      _x = self.right_hand.palm_velocity.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d2f2B().pack(_x.right_hand.palm_velocity.vector.x, _x.right_hand.palm_velocity.vector.y, _x.right_hand.palm_velocity.vector.z, _x.right_hand.sphere_radius, _x.right_hand.pinch_strength, _x.right_hand.key_tap, _x.extended_fingers))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_hand is None:
        self.left_hand = leap_motion_controller.msg.Hand()
      if self.right_hand is None:
        self.right_hand = leap_motion_controller.msg.Hand()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.left_hand.is_present, _x.left_hand.palm_pose.header.seq, _x.left_hand.palm_pose.header.stamp.secs, _x.left_hand.palm_pose.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.left_hand.is_present = bool(self.left_hand.is_present)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.palm_pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.left_hand.palm_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.left_hand.palm_pose.pose.position.x, _x.left_hand.palm_pose.pose.position.y, _x.left_hand.palm_pose.pose.position.z, _x.left_hand.palm_pose.pose.orientation.x, _x.left_hand.palm_pose.pose.orientation.y, _x.left_hand.palm_pose.pose.orientation.z, _x.left_hand.palm_pose.pose.orientation.w, _x.left_hand.palm_velocity.header.seq, _x.left_hand.palm_velocity.header.stamp.secs, _x.left_hand.palm_velocity.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.palm_velocity.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.left_hand.palm_velocity.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 46
      (_x.left_hand.palm_velocity.vector.x, _x.left_hand.palm_velocity.vector.y, _x.left_hand.palm_velocity.vector.z, _x.left_hand.sphere_radius, _x.left_hand.pinch_strength, _x.left_hand.key_tap, _x.right_hand.is_present, _x.right_hand.palm_pose.header.seq, _x.right_hand.palm_pose.header.stamp.secs, _x.right_hand.palm_pose.header.stamp.nsecs,) = _get_struct_3d2f2B3I().unpack(str[start:end])
      self.left_hand.key_tap = bool(self.left_hand.key_tap)
      self.right_hand.is_present = bool(self.right_hand.is_present)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.palm_pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.right_hand.palm_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.right_hand.palm_pose.pose.position.x, _x.right_hand.palm_pose.pose.position.y, _x.right_hand.palm_pose.pose.position.z, _x.right_hand.palm_pose.pose.orientation.x, _x.right_hand.palm_pose.pose.orientation.y, _x.right_hand.palm_pose.pose.orientation.z, _x.right_hand.palm_pose.pose.orientation.w, _x.right_hand.palm_velocity.header.seq, _x.right_hand.palm_velocity.header.stamp.secs, _x.right_hand.palm_velocity.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.palm_velocity.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.right_hand.palm_velocity.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.right_hand.palm_velocity.vector.x, _x.right_hand.palm_velocity.vector.y, _x.right_hand.palm_velocity.vector.z, _x.right_hand.sphere_radius, _x.right_hand.pinch_strength, _x.right_hand.key_tap, _x.extended_fingers,) = _get_struct_3d2f2B().unpack(str[start:end])
      self.right_hand.key_tap = bool(self.right_hand.key_tap)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d2f2B = None
def _get_struct_3d2f2B():
    global _struct_3d2f2B
    if _struct_3d2f2B is None:
        _struct_3d2f2B = struct.Struct("<3d2f2B")
    return _struct_3d2f2B
_struct_3d2f2B3I = None
def _get_struct_3d2f2B3I():
    global _struct_3d2f2B3I
    if _struct_3d2f2B3I is None:
        _struct_3d2f2B3I = struct.Struct("<3d2f2B3I")
    return _struct_3d2f2B3I
_struct_7d3I = None
def _get_struct_7d3I():
    global _struct_7d3I
    if _struct_7d3I is None:
        _struct_7d3I = struct.Struct("<7d3I")
    return _struct_7d3I
_struct_B3I = None
def _get_struct_B3I():
    global _struct_B3I
    if _struct_B3I is None:
        _struct_B3I = struct.Struct("<B3I")
    return _struct_B3I
