# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robotont_msgs/LaserScanSplit.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class LaserScanSplit(genpy.Message):
  _md5sum = "e8be98bfd4e98a5f589a43bafb13b609"
  _type = "robotont_msgs/LaserScanSplit"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
#This msg defines a message for dividing laserscan into 3 separate distances
#It provides mean and minimum values for the three sectors.

time stamp

float64 leftMin
float64 centerMin
float64 rightMin

float64 leftMean
float64 centerMean
float64 rightMean
"""
  __slots__ = ['stamp','leftMin','centerMin','rightMin','leftMean','centerMean','rightMean']
  _slot_types = ['time','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,leftMin,centerMin,rightMin,leftMean,centerMean,rightMean

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LaserScanSplit, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.leftMin is None:
        self.leftMin = 0.
      if self.centerMin is None:
        self.centerMin = 0.
      if self.rightMin is None:
        self.rightMin = 0.
      if self.leftMean is None:
        self.leftMean = 0.
      if self.centerMean is None:
        self.centerMean = 0.
      if self.rightMean is None:
        self.rightMean = 0.
    else:
      self.stamp = genpy.Time()
      self.leftMin = 0.
      self.centerMin = 0.
      self.rightMin = 0.
      self.leftMean = 0.
      self.centerMean = 0.
      self.rightMean = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I6d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.leftMin, _x.centerMin, _x.rightMin, _x.leftMean, _x.centerMean, _x.rightMean))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.stamp.secs, _x.stamp.nsecs, _x.leftMin, _x.centerMin, _x.rightMin, _x.leftMean, _x.centerMean, _x.rightMean,) = _get_struct_2I6d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I6d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.leftMin, _x.centerMin, _x.rightMin, _x.leftMean, _x.centerMean, _x.rightMean))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.stamp.secs, _x.stamp.nsecs, _x.leftMin, _x.centerMin, _x.rightMin, _x.leftMean, _x.centerMean, _x.rightMean,) = _get_struct_2I6d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I6d = None
def _get_struct_2I6d():
    global _struct_2I6d
    if _struct_2I6d is None:
        _struct_2I6d = struct.Struct("<2I6d")
    return _struct_2I6d
